{% set name = "physiocurve" %}
{% set version = "2024.9.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99b8a21c0b16c9fb5c5d173e0c824fa5a612873f240f5b777dff054953582ad6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - poetry >=0.12
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pandas >=2,<3
    - neurokit2 >=0.2.7,<0.3

test:
  imports:
    - physiocurve
    - physiocurve.pandas
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://framagit.org/jaj/physiocurve
  summary: Library to analyze biometric time series for Python
  description: |
    physiocurve is a library to analyze biometric time series such as ECG and
    pulse waves, often obtained from patient monitors.
  license: ISC
  license_file: LICENSE
  dev_url: https://framagit.org/jaj/physiocurve

extra:
  recipe-maintainers:
    - jaj42
