{% set name = "physiocurve" %}
{% set version = "2024.12.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef614e7163d7b5a7df17c31f6a7063e0c906ef5453f80367d7c73abddaae534e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.9,<3.13
    - pip
    - poetry >=0.12
    - setuptools
  run:
    - python >=3.9,<3.13
    - pandas >=2,<3
    - neurokit2 >=0.2.7,<0.3

test:
  imports:
    - physiocurve
    - physiocurve.pandas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://framagit.org/jaj/physiocurve
  summary: Library to analyze biometric time series for Python
  description: |
    physiocurve is a library to analyze biometric time series such as ECG and
    pulse waves, often obtained from patient monitors.
  license: ISC
  license_file: LICENSE
  dev_url: https://framagit.org/jaj/physiocurve

extra:
  recipe-maintainers:
    - jaj42
